name: CI/CD 
on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: CICD
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Get Env and Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
