name: CI/CD 
on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: CICD
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{ secrets.HOST_DNS }}
          USER_NAME: ${{ secrets.USERNAME }}
        with:
          hosts: '${USER_NAME}@${HOSTNAME}'
          privateKey: ${{ secrets.PRIVATE_KEY }}
          debug: false
          command: |
            ls -lah
            hostname -a
            whoami
            touch helloworld.txt

    
   
     
