name: CI/CD 
on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: CICD
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Env and Deploy in EC2
        uses: JimCronqvist/action-ssh@master
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
        with:
            hosts: '${USER_NAME}@${HOSTNAME}'
            privateKey: ${{ secrets.PRIVATE_KEY }}
            debug: false
            command: |
              ls -lah
              hostname -a
              whoami
