name: CI/CD

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    name: CICD
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Get Env Value
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Deploy to EC2 Server
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile /dev/null" -i private_key ${USER_NAME}@${HOSTNAME} '
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ec2-user/deployment &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main
